<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 (http://www.altova.com) by siarheig (HOME) -->
<definitions xmlns:tns="http://www.sigma-systems.com/schemas/3.1/SmpXmlOrderAPI" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://www.sigma-systems.com/schemas/3.1/SmpXmlOrderAPI">
    <types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.sigma-systems.com/schemas/3.1/SmpXmlOrderAPI"></xsd:schema>
    </types>
    <message name="executeXml">
        <part name="xmlRequest" type="partns:string" xmlns:partns="http://www.w3.org/2001/XMLSchema"></part>
    </message>
    <message name="executeXmlResponse">
        <part name="xmlResponse" type="partns:string" xmlns:partns="http://www.w3.org/2001/XMLSchema"></part>
    </message>
    <portType name="xmlorderPort">
        <operation name="executeXml">
            <input message="tns:executeXml"></input>
            <output message="tns:executeXmlResponse"></output>
        </operation>
    </portType>
    <binding name="xmlorderPort" type="tns:xmlorderPort">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="executeXml">
            <soap:operation soapAction="executeXml"/>
            <input>
                <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" 
                namespace="http://www.sigma-systems.com/schemas/3.1/SmpXmlOrderAPI"/>
            </input>
            <output>
                <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" 
                namespace="http://www.sigma-systems.com/schemas/3.1/SmpXmlOrderAPI"/>
            </output>
        </operation>
    </binding>
    <service name="xmlorder">
        <port name="xmlorderPort" binding="tns:xmlorderPort">
            <soap:address location="http://localhost:8088/SmpXmlOrderApi/xmlorder"/>
        </port>
    </service>
</definitions>
